# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/birdview_modal.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Modal(object):
    def setupUi(self, Modal):
        Modal.setObjectName("Modal")
        Modal.setWindowModality(QtCore.Qt.WindowModal)
        Modal.resize(322, 83)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icons/mainlogo_sm.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        Modal.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Modal)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 301, 61))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.modalInputBox = QtWidgets.QPlainTextEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modalInputBox.sizePolicy().hasHeightForWidth())
        self.modalInputBox.setSizePolicy(sizePolicy)
        self.modalInputBox.setMaximumSize(QtCore.QSize(16777215, 30))
        self.modalInputBox.setBackgroundVisible(True)
        self.modalInputBox.setObjectName("modalInputBox")
        self.verticalLayout.addWidget(self.modalInputBox)
        Modal.setCentralWidget(self.centralwidget)

        self.retranslateUi(Modal)
        QtCore.QMetaObject.connectSlotsByName(Modal)

    def retranslateUi(self, Modal):
        _translate = QtCore.QCoreApplication.translate
        Modal.setWindowTitle(_translate("Modal", "Birdview"))
        self.label.setText(_translate("Modal", "Enter value:"))
import ui.resource_rc
